export type QuizQuestion = {
  id: number;
  question: string;
  statements?: Record<string, string>;
  options: string[];
  correct: number;
  explanation: string;
};

export type QuizData = {
  title: string;
  duration: number;
  negativeMarking: number;
  cutoff: number;
  questions: QuizQuestion[];
};

type PairSeed = {
  topic: string;
  category: string;
  one: string;
  two: string;
  correct: 0 | 1 | 2 | 3;
  why: string;
};

export type QuizSet = {
  slug: string;
  title: string;
  description: string;
  categories: string[];
  quiz: QuizData;
};

const PAIR_OPTIONS = [
  "1 only",
  "2 only",
  "Both 1 and 2",
  "Neither 1 nor 2",
];

function buildQuiz(title: string, seeds: PairSeed[], duration = 600): QuizData {
  return {
    title,
    duration,
    negativeMarking: 0.333,
    cutoff: Math.ceil(seeds.length * 0.6),
    questions: seeds.map((seed, index) => ({
      id: index + 1,
      question: `With reference to ${seed.topic}, consider the following statements:`,
      statements: { "1": seed.one, "2": seed.two },
      options: PAIR_OPTIONS,
      correct: seed.correct,
      explanation: seed.why,
    })),
  };
}

function makeSets(monthLabel: string, seeds: PairSeed[]): QuizSet[] {
  return Array.from({ length: 5 }, (_, index) => {
    const questions = seeds.slice(index * 5, index * 5 + 5);
    return {
      slug: `set-${index + 1}-english`,
      title: `${monthLabel} 2026 - Quiz ${index + 1}`,
      description: "Five UPSC-level statement questions with current-static linkages.",
      categories: [...new Set(questions.map((question) => question.category))],
      quiz: buildQuiz(`${monthLabel} 2026 - Quiz ${index + 1}`, questions, 600),
    };
  });
}

const JANUARY: PairSeed[] = [
  { topic: "the BBNJ Agreement", category: "world", one: "It is an implementing agreement under the United Nations Convention on the Law of the Sea.", two: "It concerns biodiversity in marine areas beyond national jurisdiction.", correct: 2, why: "Both are correct. The BBNJ or High Seas Treaty operates under UNCLOS and covers conservation and sustainable use of biodiversity beyond national jurisdiction." },
  { topic: "Census 2027", category: "polity", one: "Population census is a Union subject under the Seventh Schedule.", two: "The Registrar General and Census Commissioner functions under the Ministry of Home Affairs.", correct: 2, why: "Both are correct. Census is in the Union List and the census machinery is administered through the Office of the Registrar General under the Home Ministry." },
  { topic: "Bulgaria adopting the euro", category: "world", one: "Membership of the European Union automatically makes a country part of the euro area from the date it joins the EU.", two: "The European Central Bank conducts monetary policy for the euro area.", correct: 1, why: "Statement 1 is incorrect because EU members must satisfy convergence requirements and formally enter the euro area. Statement 2 is correct." },
  { topic: "the Pralay missile", category: "st", one: "Pralay is an Indian surface-to-surface quasi-ballistic missile.", two: "It was designed primarily as a submarine-launched ballistic missile for nuclear deterrence patrols.", correct: 0, why: "Only statement 1 is correct. Pralay is a conventional surface-to-surface system; submarine-launched deterrent missiles belong to a different family." },
  { topic: "scramjet propulsion", category: "st", one: "A scramjet is an air-breathing engine in which combustion occurs in supersonic airflow.", two: "A scramjet must carry both fuel and atmospheric oxygen in onboard tanks.", correct: 0, why: "Only statement 1 is correct. Scramjets use atmospheric oxygen, reducing the need to carry an oxidiser like a rocket." },
  { topic: "Atal Pension Yojana", category: "economy", one: "The scheme is administered by the Pension Fund Regulatory and Development Authority.", two: "It is designed mainly to extend pension security to workers in the unorganised sector.", correct: 2, why: "Both statements are correct. APY is a PFRDA-administered defined-benefit social-security scheme focused on unorganised workers." },
  { topic: "SIDBI", category: "economy", one: "SIDBI is the principal financial institution for promotion, financing and development of the MSME sector.", two: "SIDBI was created directly by a constitutional amendment and is audited only by the Finance Commission.", correct: 0, why: "Only statement 1 is correct. SIDBI is a statutory development financial institution established under the SIDBI Act, 1989, not a constitutional body." },
  { topic: "the Indian Carbon Market", category: "env", one: "Its compliance framework is linked to the Energy Conservation Act.", two: "The Bureau of Energy Efficiency has a role in the carbon credit trading framework.", correct: 2, why: "Both are correct. The Energy Conservation Act provides the legal basis and BEE is a central implementing institution in the carbon market architecture." },
  { topic: "ECINET", category: "polity", one: "It is intended to integrate digital services of the Election Commission of India.", two: "The Election Commission derives its constitutional status from Article 324.", correct: 2, why: "Both are correct. ECINET consolidates election-management services, while Article 324 vests election superintendence, direction and control in the ECI." },
  { topic: "the SAMPANN portal", category: "polity", one: "It is associated with pension management for Department of Telecommunications pensioners.", two: "It is administered by the Ministry of Personnel as the universal pension portal for every civil servant.", correct: 0, why: "Only statement 1 is correct. SAMPANN is a telecom pension accounting and payment platform, not the universal civil-service pension portal." },
  { topic: "India's Military Quantum Mission", category: "st", one: "Quantum communication can support highly secure military links.", two: "Quantum sensing has no plausible application in navigation or detection.", correct: 0, why: "Only statement 1 is correct. Quantum sensing is relevant to precision navigation, timing and detection in addition to secure communications." },
  { topic: "mine tailings and critical minerals", category: "env", one: "Tailings are residual materials left after valuable minerals are separated from ore.", two: "Recovering critical minerals from tailings can reduce the need for fresh extraction and address legacy waste.", correct: 2, why: "Both are correct. Reprocessing tailings can turn mine waste into a secondary resource while lowering some environmental pressures." },
  { topic: "open-sea marine fish farming", category: "env", one: "It is a form of mariculture rather than inland aquaculture.", two: "Poorly managed open-sea cages can create nutrient loading and disease risks.", correct: 2, why: "Both are correct. Offshore cage farming is mariculture and requires ecological safeguards for waste, disease and carrying capacity." },
  { topic: "Meghalaya's living root bridges", category: "history", one: "They are created by training the aerial roots of rubber fig trees across streams.", two: "They represent a living indigenous engineering tradition associated with Khasi and Jaintia communities.", correct: 2, why: "Both are correct. The bridges combine bioengineering with community knowledge and are grown rather than conventionally constructed." },
  { topic: "Parakram Diwas", category: "history", one: "It is observed on 23 January to mark the birth anniversary of Subhas Chandra Bose.", two: "Bose founded the Forward Bloc after resigning from the Congress presidency.", correct: 2, why: "Both are correct. Parakram Diwas commemorates Bose, whose later political path included forming the Forward Bloc in 1939." },
  { topic: "National Startup Day", category: "economy", one: "It is observed in India on 16 January.", two: "Startup India is administered by the Department for Promotion of Industry and Internal Trade.", correct: 2, why: "Both are correct. The observance marks the launch of Startup India, and DPIIT manages recognition and core policy support." },
  { topic: "the Export Preparedness Index", category: "economy", one: "It is released by NITI Aayog to compare export ecosystems of States and Union Territories.", two: "It measures only the value of merchandise exports and excludes policy or infrastructure indicators.", correct: 0, why: "Only statement 1 is correct. The index is multidimensional and examines policy, business ecosystem, export ecosystem and performance." },
  { topic: "vehicle-to-vehicle communication", category: "st", one: "V2V can allow vehicles to exchange information about position, speed and hazards.", two: "Its road-safety use is independent of spectrum, standards and cybersecurity safeguards.", correct: 0, why: "Only statement 1 is correct. Reliable V2V deployment depends on interoperable standards, communications spectrum and strong cybersecurity." },
  { topic: "3D-printed automatic weather stations", category: "st", one: "Additive manufacturing can reduce part count and enable rapid local production.", two: "An automatic weather station generally records variables such as temperature, humidity, wind and rainfall.", correct: 2, why: "Both are correct. 3D printing can make station hardware faster to produce, while sensors automate meteorological observation." },
  { topic: "Niryat Protsahan interventions", category: "economy", one: "The term niryat refers to exports.", two: "Export promotion can include credit, market-access and logistics support rather than tariff protection alone.", correct: 2, why: "Both are correct. Export competitiveness rests on finance, standards, logistics and market access, not merely import tariffs." },
  { topic: "recirculating aquaculture systems", category: "env", one: "RAS treats and reuses water within a controlled aquaculture facility.", two: "RAS eliminates all energy requirements because water moves only through natural gravity.", correct: 0, why: "Only statement 1 is correct. Pumps, filtration, aeration and temperature control can make RAS energy intensive." },
  { topic: "the India-Pakistan exchange of nuclear-installation lists", category: "world", one: "The exchange is carried out annually on 1 January under a bilateral agreement.", two: "The agreement seeks to prohibit attacks against nuclear installations and facilities.", correct: 2, why: "Both are correct. The 1988 bilateral agreement creates an annual notification mechanism and a mutual non-attack obligation." },
  { topic: "Somnath Temple", category: "history", one: "The present temple is located on the coast of Gujarat.", two: "Its post-Independence reconstruction is associated with Sardar Vallabhbhai Patel and K. M. Munshi.", correct: 2, why: "Both are correct. Somnath's modern reconstruction became a major post-Independence civilisational project." },
  { topic: "the ONDC monument-ticketing initiative", category: "history", one: "ONDC is an interoperable network rather than a single inventory-owning e-commerce platform.", two: "The Archaeological Survey of India works under the Ministry of Culture.", correct: 2, why: "Both are correct. ONDC uses open protocols, while ASI is the Union government's principal archaeological organisation under the Culture Ministry." },
  { topic: "the Mpemba effect", category: "st", one: "It refers to circumstances in which initially hotter water may freeze faster than colder water.", two: "It is a universal law that occurs under every set of experimental conditions.", correct: 0, why: "Only statement 1 is correct. The effect depends on experimental conditions and competing processes such as evaporation, convection and supercooling." },
];

const FEBRUARY: PairSeed[] = [
  { topic: "National Waterway-2", category: "geo", one: "It is located on the Brahmaputra river system.", two: "It extends through Assam and is strategically important for inland navigation in the Northeast.", correct: 2, why: "Both are correct. National Waterway-2 follows the Brahmaputra and is central to multimodal connectivity in Assam and the wider Northeast." },
  { topic: "India-Bhutan hydropower cooperation", category: "world", one: "Bhutan's hydropower exports are an important component of its economic relationship with India.", two: "Run-of-river hydropower projects can have no ecological or sediment impacts by definition.", correct: 0, why: "Only statement 1 is correct. Run-of-river projects may have smaller reservoirs but can still affect flows, sediments and river ecology." },
  { topic: "India-Nepal biodiversity cooperation", category: "env", one: "India and Nepal share transboundary landscapes in the Himalayan and Terai regions.", two: "Wildlife corridors can require coordination across administrative and international boundaries.", correct: 2, why: "Both are correct. Species movement and ecosystem continuity make cross-border forest and wildlife cooperation necessary." },
  { topic: "Exercise Vajra Prahar", category: "world", one: "It is a bilateral special-forces exercise between India and the United States.", two: "It is primarily a multilateral naval anti-piracy exercise held under IORA.", correct: 0, why: "Only statement 1 is correct. Vajra Prahar is an India-US Army special-forces exercise, not an IORA naval drill." },
  { topic: "Exercise Dharma Guardian", category: "world", one: "It is a bilateral army exercise between India and Japan.", two: "Its existence reflects the growing security dimension of the India-Japan Special Strategic and Global Partnership.", correct: 2, why: "Both are correct. Dharma Guardian trains the two armies and sits within a wider expansion of bilateral defence ties." },
  { topic: "National Monetisation Pipeline 2.0", category: "economy", one: "Asset monetisation can transfer a revenue right without transferring ownership of the underlying public asset.", two: "Asset monetisation and outright privatisation are necessarily identical transactions.", correct: 0, why: "Only statement 1 is correct. Monetisation often recycles brownfield asset value through leases or concessions while public ownership may remain." },
  { topic: "PRAHAAR counter-terrorism policy", category: "polity", one: "A national counter-terrorism framework must coordinate intelligence, investigation, border management and terror-financing controls.", two: "Public order and police are entries in the Union List alone.", correct: 0, why: "Only statement 1 is correct. Police and public order are State List subjects, making Centre-State coordination indispensable." },
  { topic: "the HCL-Foxconn semiconductor unit", category: "st", one: "Semiconductor assembly and testing are downstream stages distinct from wafer fabrication.", two: "Every semiconductor manufacturing project necessarily begins with leading-edge logic-chip fabrication.", correct: 0, why: "Only statement 1 is correct. The value chain includes design, fabrication, packaging, assembly and testing, and projects may specialise in different stages." },
  { topic: "Vibrant Villages Programme-II", category: "polity", one: "Border-area development can support both livelihoods and strategic resilience.", two: "Such programmes are confined constitutionally to cantonment areas administered by the Defence Ministry.", correct: 0, why: "Only statement 1 is correct. Vibrant Villages addresses civilian settlements in strategic border areas, not only military cantonments." },
  { topic: "the Central Consumer Protection Authority", category: "polity", one: "The CCPA was created under the Consumer Protection Act, 2019.", two: "It can act against misleading advertisements and unfair trade practices affecting consumers as a class.", correct: 2, why: "Both are correct. CCPA is a statutory regulator with investigation, recall, refund and advertising-related powers." },
  { topic: "Gaganyaan drogue parachutes", category: "st", one: "Drogue parachutes help stabilise and decelerate a returning crew module before main parachutes deploy.", two: "They are used to provide orbital propulsion after the launch vehicle reaches space.", correct: 0, why: "Only statement 1 is correct. Drogue parachutes are part of atmospheric descent and recovery, not orbital propulsion." },
  { topic: "the Great Nicobar development project", category: "env", one: "Great Nicobar lies in the Andaman and Nicobar archipelago and includes ecologically sensitive habitats.", two: "Environmental clearance removes the need for subsequent compliance monitoring and mitigation.", correct: 0, why: "Only statement 1 is correct. Clearance is conditional and requires continuing compliance, monitoring and mitigation." },
  { topic: "VoicERA on BHASHINI", category: "st", one: "BHASHINI seeks to expand digital services across Indian languages using language technologies.", two: "Voice AI requires only speech synthesis and has no need for speech recognition or language models.", correct: 0, why: "Only statement 1 is correct. A voice stack can combine speech recognition, translation, language understanding and speech synthesis." },
  { topic: "MILAN 2026", category: "world", one: "MILAN is a multilateral naval exercise hosted by India.", two: "The exercise contributes to interoperability and maritime cooperation among participating navies.", correct: 2, why: "Both are correct. MILAN is an Indian-hosted multilateral naval engagement focused on professional exchange and operational coordination." },
  { topic: "bee corridors along highways", category: "env", one: "Pollinator-friendly native vegetation can improve habitat connectivity in fragmented landscapes.", two: "Roadside ecological planting is risk-free and never requires control of invasive species or pesticide exposure.", correct: 0, why: "Only statement 1 is correct. Corridor design must manage invasives, collisions, pesticides and local ecological suitability." },
  { topic: "the India-UK offshore wind taskforce", category: "env", one: "Offshore wind generally benefits from stronger and more consistent winds than many onshore sites.", two: "Offshore wind development can involve seabed, grid, fisheries and coastal-zone considerations.", correct: 2, why: "Both are correct. Offshore resources are attractive but require complex marine spatial planning and transmission infrastructure." },
  { topic: "a squat lobster discovery in Lakshadweep", category: "env", one: "Squat lobsters are decapod crustaceans but are not true lobsters.", two: "Island and seamount ecosystems can harbour high levels of endemism and poorly documented biodiversity.", correct: 2, why: "Both are correct. Taxonomic discoveries around oceanic islands highlight the biological richness and research gaps of marine habitats." },
  { topic: "the AI Impact Summit 2026", category: "st", one: "New Delhi hosted the summit as a major Global South platform for artificial-intelligence governance and deployment.", two: "AI governance questions can include safety, inclusion, compute access, data and labour-market effects.", correct: 2, why: "Both are correct. The summit's significance was not limited to technology showcases; it also covered governance and development concerns." },
  { topic: "the New Delhi Declaration on AI", category: "world", one: "International AI declarations are politically influential even when they are not automatically binding treaties.", two: "A declaration becomes enforceable domestic criminal law in every signatory country without legislation.", correct: 0, why: "Only statement 1 is correct. Declarations can shape norms and cooperation but generally require domestic legal action to create enforceable obligations." },
  { topic: "the Khelo India Winter Games", category: "geo", one: "Winter-sport infrastructure is closely linked to high-altitude climate and seasonal snow conditions.", two: "Khelo India is a Union initiative for sports development and competitive exposure.", correct: 2, why: "Both are correct. The winter edition combines geographic suitability with the broader Khelo India athlete-development ecosystem." },
  { topic: "RailTech policy", category: "st", one: "Railway technology policy can promote indigenous innovation in signalling, rolling stock, safety and maintenance.", two: "Railway safety technology is unrelated to communications and data systems.", correct: 0, why: "Only statement 1 is correct. Modern rail safety depends heavily on signalling, telecom, sensors and data-driven maintenance." },
  { topic: "the India-France Special Global Strategic Partnership", category: "world", one: "India and France cooperate in defence, space, civil nuclear energy and the Indo-Pacific.", two: "France has no sovereign territory or exclusive economic zone in the Indian Ocean.", correct: 0, why: "Only statement 1 is correct. France is an Indian Ocean resident power through overseas territories and a large regional EEZ." },
  { topic: "the Namo Bharat corridor", category: "geo", one: "Namo Bharat is associated with regional rapid transit rather than a conventional urban metro alone.", two: "Regional rapid transit is intended to connect cities across a wider commuter region at higher average speeds.", correct: 2, why: "Both are correct. RRTS differs from typical metro systems in stop spacing, speed and inter-city regional function." },
  { topic: "the Rail Parcel mobile application", category: "economy", one: "Digitising parcel logistics can improve booking visibility, tracking and first-mile or last-mile coordination.", two: "Rail parcel services carry only passenger baggage and cannot support commercial consignments.", correct: 0, why: "Only statement 1 is correct. Railways also move commercial parcels, and digitisation can expand their logistics role." },
  { topic: "the India-Sweden green technology partnership", category: "env", one: "Industrial decarbonisation can involve green hydrogen, low-carbon steel, electrification and circular manufacturing.", two: "Technology partnerships alone eliminate the need for standards, finance and carbon-accounting systems.", correct: 0, why: "Only statement 1 is correct. Deployment also depends on policy, finance, infrastructure, measurement and markets." },
];

const MARCH: PairSeed[] = [
  { topic: "India's first fully digital census", category: "polity", one: "Digital self-enumeration can supplement, but does not by itself eliminate, field enumeration.", two: "Census operations in India are governed by the Census Act, 1948.", correct: 2, why: "Both are correct. Digital tools can widen participation and improve processing while the statutory census framework and field machinery remain essential." },
  { topic: "Energy Statistics India 2026", category: "economy", one: "Energy statistics distinguish primary energy sources from electricity, which is a secondary energy form.", two: "Installed electricity capacity and actual electricity generation are identical measures.", correct: 0, why: "Only statement 1 is correct. Capacity measures maximum potential output, while generation measures electricity actually produced over time." },
  { topic: "IONS Maritime Exercise 2026", category: "world", one: "IONS stands for Indian Ocean Naval Symposium.", two: "Table-top exercises can test coordination and decision-making without deploying a full operational fleet.", correct: 2, why: "Both are correct. IONS is an Indian Ocean maritime forum, and a TTX rehearses procedures through simulated scenarios." },
  { topic: "RBI Payments Vision 2028", category: "economy", one: "A payments vision can address resilience, fraud prevention, inclusion and cross-border interoperability.", two: "The Reserve Bank has no regulatory role in payment and settlement systems.", correct: 0, why: "Only statement 1 is correct. RBI regulates and oversees payment systems under the Payment and Settlement Systems Act, 2007." },
  { topic: "India's updated NDC targets", category: "env", one: "Nationally Determined Contributions are submitted under the Paris Agreement.", two: "Every NDC target is imposed identically on all countries by the UN Security Council.", correct: 0, why: "Only statement 1 is correct. NDCs are nationally determined climate commitments, reflecting differentiated national circumstances." },
  { topic: "a State Uniform Civil Code", category: "polity", one: "Personal laws fall in the Concurrent List.", two: "A State law on a Concurrent List subject can never require consideration of repugnancy with an existing parliamentary law.", correct: 0, why: "Only statement 1 is correct. State legislation in the concurrent field must be assessed under Article 254 and may require presidential assent where repugnancy arises." },
  { topic: "the modified UDAN scheme", category: "economy", one: "UDAN seeks to improve regional air connectivity to underserved and unserved airports.", two: "Viability-gap funding can support routes that are socially useful but initially commercially weak.", correct: 2, why: "Both are correct. UDAN combines regional connectivity obligations with financial and operational support." },
  { topic: "District Mineral Foundations", category: "polity", one: "DMFs are statutory non-profit trusts linked to mining-affected districts.", two: "Their legal basis arises from amendments to the Mines and Minerals (Development and Regulation) Act.", correct: 2, why: "Both are correct. DMFs use mining-linked contributions for the welfare of people and areas affected by mining." },
  { topic: "NASA's Artemis programme", category: "st", one: "Artemis seeks sustained human exploration of the Moon and supports preparation for later Mars missions.", two: "The programme excludes international partners and commercial launch or lander providers by design.", correct: 0, why: "Only statement 1 is correct. Artemis involves international partnerships, the Artemis Accords and major commercial participation." },
  { topic: "World Tuberculosis Day", category: "st", one: "It is observed on 24 March, linked to Robert Koch's announcement of the tuberculosis bacillus.", two: "Tuberculosis is caused by a virus and therefore cannot develop antimicrobial resistance.", correct: 0, why: "Only statement 1 is correct. TB is a bacterial disease caused by Mycobacterium tuberculosis and drug-resistant forms are a major challenge." },
  { topic: "International Day of Forests", category: "env", one: "It is observed on 21 March.", two: "Forests influence carbon storage, water cycles, biodiversity and local livelihoods.", correct: 2, why: "Both are correct. The observance highlights forests' combined ecological, climatic and socio-economic roles." },
  { topic: "the GlobE Network", category: "world", one: "It supports cooperation among law-enforcement authorities against corruption.", two: "It functions as a judicial chamber of the International Court of Justice.", correct: 0, why: "Only statement 1 is correct. GlobE is a cooperation network, not a court or adjudicatory body." },
  { topic: "invasive alien species governance", category: "env", one: "An alien species becomes invasive when its introduction or spread threatens biodiversity or related interests.", two: "Every non-native species is automatically invasive regardless of impact or spread.", correct: 0, why: "Only statement 1 is correct. Alien status alone is insufficient; invasiveness relates to establishment, spread and harm." },
  { topic: "RBI's Utkarsh 3.0", category: "economy", one: "Utkarsh is associated with the Reserve Bank's medium-term strategy and institutional strengthening.", two: "It is a Central government scheme for universal crop insurance.", correct: 0, why: "Only statement 1 is correct. Utkarsh is RBI's organisational strategy framework, not an agricultural insurance programme." },
  { topic: "postal ballots in Indian elections", category: "polity", one: "Postal-ballot voting is available only to categories specified by election law and rules.", two: "The Election Commission may administer postal-ballot processes under its Article 324 responsibilities subject to law.", correct: 2, why: "Both are correct. The facility is rule-based, while ECI supervises implementation within the statutory framework." },
  { topic: "small hydropower", category: "env", one: "Small hydropower is classified as renewable energy in India.", two: "Small projects are automatically exempt from every environmental and river-basin safeguard.", correct: 0, why: "Only statement 1 is correct. Project scale does not erase possible cumulative, flow, biodiversity or community impacts." },
  { topic: "the UN child-mortality estimates", category: "polity", one: "The under-five mortality rate measures deaths before age five per 1,000 live births.", two: "A decline in mortality can coexist with wide inequalities across regions and income groups.", correct: 2, why: "Both are correct. National progress can mask subnational and socio-economic disparities." },
  { topic: "the BHAVYA industrial-development scheme", category: "economy", one: "Industrial policy can combine infrastructure, cluster development, logistics and investment facilitation.", two: "Manufacturing competitiveness depends only on the statutory corporate-tax rate.", correct: 0, why: "Only statement 1 is correct. Skills, technology, infrastructure, finance, regulation and supply chains also shape competitiveness." },
  { topic: "IOS SAGAR", category: "world", one: "The initiative uses an Indian naval ship with personnel from partner countries for cooperative maritime deployment.", two: "SAGAR expresses India's vision of Security and Growth for All in the Region.", correct: 2, why: "Both are correct. IOS SAGAR turns the wider SAGAR vision into shared training, deployment and maritime cooperation." },
  { topic: "the ALMM framework", category: "env", one: "ALMM is used to identify approved models and manufacturers for solar photovoltaic equipment.", two: "Expanding it to more components can support traceability and domestic supply-chain goals.", correct: 2, why: "Both are correct. The framework links procurement eligibility with approved manufacturing sources and quality control." },
  { topic: "hydrogen production and desalination materials", category: "st", one: "Electrocatalysts can lower the energy barrier for water-splitting reactions.", two: "Desalination always produces fresh water without brine or energy inputs.", correct: 0, why: "Only statement 1 is correct. Desalination requires energy and produces concentrated brine that needs responsible management." },
  { topic: "maternity benefits for adoptive mothers", category: "polity", one: "Article 14 permits reasonable classification but prohibits arbitrary discrimination.", two: "Adoption-related maternity support can be examined through equality, dignity and child-welfare principles.", correct: 2, why: "Both are correct. Constitutional review may assess whether distinctions between biological and adoptive motherhood are rational and non-arbitrary." },
  { topic: "the Appropriation Bill", category: "polity", one: "Article 114 concerns appropriation of money out of the Consolidated Fund of India.", two: "No money can be withdrawn from that Fund except under appropriation made by law, subject to constitutional exceptions.", correct: 2, why: "Both are correct. Legislative authorisation through appropriation is a core element of parliamentary financial control." },
  { topic: "the IVFRT scheme", category: "polity", one: "IVFRT integrates immigration, visa, foreigner registration and tracking functions.", two: "Immigration and citizenship are exclusively State List subjects.", correct: 0, why: "Only statement 1 is correct. Citizenship, naturalisation and aliens fall within the Union domain." },
  { topic: "the WTO outlook for global trade", category: "economy", one: "Merchandise trade volume and merchandise trade value can move differently because prices and exchange rates change.", two: "A slowdown in trade growth necessarily means the absolute level of world trade has fallen.", correct: 0, why: "Only statement 1 is correct. Slower growth can still mean trade is expanding, just at a lower rate." },
];

const APRIL: PairSeed[] = [
  { topic: "the NASM-SR missile", category: "st", one: "It is an indigenous naval anti-ship missile designed for short-range engagement.", two: "An anti-ship missile may combine inertial navigation with terminal guidance for a moving maritime target.", correct: 2, why: "Both are correct. NASM-SR strengthens indigenous air-launched anti-ship capability and requires accurate terminal targeting." },
  { topic: "Women and Men in India 2025", category: "polity", one: "The publication is issued by the Ministry of Statistics and Programme Implementation.", two: "Gender-disaggregated statistics can reveal differences that national averages conceal.", correct: 2, why: "Both are correct. MoSPI's compilation supports gender analysis across health, education, work and decision-making." },
  { topic: "global tropical forest loss", category: "env", one: "Tree-cover loss and deforestation are analytically identical in every dataset.", two: "Fire, logging, commodity expansion and shifting cultivation can have different roles across regions.", correct: 1, why: "Only statement 2 is correct. Tree-cover loss can include temporary plantation harvest or natural disturbance, while deforestation implies longer-term land-use conversion." },
  { topic: "IN-SLN DIVEX 2026", category: "world", one: "It is a diving exercise between India and Sri Lanka.", two: "Diving cooperation can cover underwater search, salvage, explosive-ordnance disposal and rescue skills.", correct: 2, why: "Both are correct. Bilateral diving drills build specialist interoperability for naval underwater tasks." },
  { topic: "RTE admissions in private schools", category: "polity", one: "Article 21A provides for free and compulsory education for children aged six to fourteen years.", two: "The RTE Act includes an entry-level reservation obligation for specified disadvantaged and weaker-section children in unaided non-minority schools.", correct: 2, why: "Both are correct. Article 21A and Section 12(1)(c) form the constitutional and statutory basis of this inclusion measure." },
  { topic: "India-New Zealand trade negotiations", category: "economy", one: "A free trade agreement generally reduces barriers on substantially all trade but can retain sensitive exclusions.", two: "An FTA automatically creates a customs union with one common external tariff.", correct: 0, why: "Only statement 1 is correct. A customs union has a common external tariff; an FTA does not necessarily do so." },
  { topic: "Ladakh's new districts", category: "polity", one: "Ladakh is a Union Territory without a legislative assembly.", two: "Creation of districts is an administrative reorganisation and does not by itself create new States under Article 3.", correct: 2, why: "Both are correct. District formation changes sub-UT administration, not the federal map of States and Union Territories." },
  { topic: "SIPRI military-expenditure rankings", category: "world", one: "SIPRI is an independent international research institute based in Stockholm.", two: "Military expenditure rankings alone measure combat effectiveness and strategic influence comprehensively.", correct: 0, why: "Only statement 1 is correct. Spending is useful but cannot by itself capture doctrine, readiness, technology, alliances or operational capability." },
  { topic: "Startup India Fund of Funds 2.0", category: "economy", one: "A fund of funds invests through other investment funds rather than directly financing every startup.", two: "Such a structure can crowd in private capital and specialised fund-management expertise.", correct: 2, why: "Both are correct. The model allocates capital to registered funds, which then invest in startups under defined conditions." },
  { topic: "malaria treatment for newborns and infants", category: "st", one: "Drug approval for very young children requires age-appropriate evidence and dosing.", two: "Malaria is transmitted by infected female Anopheles mosquitoes.", correct: 2, why: "Both are correct. Infant treatment needs tailored pharmacology, and malaria's established vector is the female Anopheles mosquito." },
  { topic: "biodiversity governance", category: "env", one: "India's Biological Diversity Act provides for national, state and local-level institutions.", two: "People's Biodiversity Registers are associated with Biodiversity Management Committees.", correct: 2, why: "Both are correct. India's biodiversity framework links the NBA, State Boards and local BMCs, including documentation of local bioresources." },
  { topic: "sustainable aviation fuel", category: "env", one: "SAF can be blended with conventional aviation turbine fuel subject to approved specifications.", two: "Its climate benefit depends partly on lifecycle emissions rather than tailpipe carbon alone.", correct: 2, why: "Both are correct. Feedstock, processing energy, land use and supply chains determine lifecycle performance." },
  { topic: "termination of pregnancy under the MTP framework", category: "polity", one: "The Medical Termination of Pregnancy Act creates conditions and gestational limits for lawful termination.", two: "Constitutional courts have never considered reproductive autonomy, dignity or the welfare of a minor in such cases.", correct: 0, why: "Only statement 1 is correct. Courts have repeatedly engaged with autonomy, dignity, health and special circumstances within the statutory framework." },
  { topic: "the India-Maldives currency-swap arrangement", category: "economy", one: "A bilateral currency swap can provide temporary foreign-exchange liquidity.", two: "It is identical to a permanent transfer that creates no repayment obligation.", correct: 0, why: "Only statement 1 is correct. A swap is a reciprocal, time-bound financial arrangement with agreed repayment and pricing terms." },
  { topic: "the India-Africa Forum Summit", category: "world", one: "IAFS is a platform for India-wide engagement with African countries and the African Union.", two: "India's Africa partnership includes development cooperation, capacity building, trade and digital public infrastructure.", correct: 2, why: "Both are correct. The summit architecture reflects a broad South-South partnership rather than a single-sector relationship." },
  { topic: "Shekha Jheel", category: "env", one: "It is a wetland in Uttar Pradesh recognised as a Ramsar Site.", two: "Ramsar designation converts a wetland into territory administered by the United Nations.", correct: 0, why: "Only statement 1 is correct. Ramsar recognition creates international conservation commitments but does not transfer sovereignty or administration." },
  { topic: "online gaming regulation", category: "polity", one: "Online gaming policy can implicate consumer protection, taxation, money laundering, child safety and State gambling laws.", two: "All online games are constitutionally treated as one uniform category regardless of skill, chance or stakes.", correct: 0, why: "Only statement 1 is correct. Indian law has historically distinguished games of skill and chance, while real-money and harm concerns add further complexity." },
  { topic: "the Prime Minister's Internship Scheme", category: "economy", one: "Internships are intended to improve workplace exposure and employability, not to guarantee a permanent job.", two: "Including final-year students can widen the transition pathway from education to work.", correct: 2, why: "Both are correct. The scheme is an exposure and skill-building mechanism rather than a legal employment guarantee." },
  { topic: "telecom design-linked innovation support", category: "st", one: "Telecom self-reliance requires design, intellectual property, testing, standards and manufacturing capabilities.", two: "Radio-access networks, optical systems and core networks are all parts of the wider telecom ecosystem.", correct: 2, why: "Both are correct. Innovation support must span the full technology stack, not only final handset assembly." },
  { topic: "Aadhaar offline verification", category: "polity", one: "Offline verification can confirm identity attributes without an online authentication transaction for every use.", two: "An offline verifier may store or share Aadhaar data without any purpose limitation or security obligation.", correct: 0, why: "Only statement 1 is correct. Verifiers remain bound by consent, purpose limitation, data minimisation and security requirements." },
  { topic: "crop procurement", category: "economy", one: "Minimum Support Prices are recommended by the Commission for Agricultural Costs and Prices.", two: "Announcement of an MSP guarantees that the government will procure every unit produced in every State.", correct: 0, why: "Only statement 1 is correct. Actual procurement varies by crop, agency, geography, quality and operational arrangements." },
  { topic: "the Bharat Maritime Insurance Pool", category: "economy", one: "Insurance pools can aggregate capacity for risks that individual insurers may find difficult to absorb.", two: "Marine insurance may cover cargo, hull and related liabilities.", correct: 2, why: "Both are correct. Pooling spreads high-severity or strategic risks and maritime insurance has several distinct classes." },
  { topic: "India's digital census self-enumeration", category: "polity", one: "Self-enumeration can reduce data-entry steps but requires accessibility, authentication and privacy safeguards.", two: "Digital census data is outside the scope of cybersecurity because it is statistical rather than financial.", correct: 0, why: "Only statement 1 is correct. Population data is sensitive and demands strong security, access control and governance." },
  { topic: "the Chernobyl anniversary", category: "env", one: "The 1986 disaster occurred in the then Ukrainian Soviet Socialist Republic.", two: "Nuclear safety includes reactor design, regulation, emergency preparedness and transboundary notification.", correct: 2, why: "Both are correct. Chernobyl remains central to global nuclear-safety and emergency-cooperation debates." },
  { topic: "the wheat procurement target", category: "economy", one: "Wheat procured for the central pool supports food-security operations and buffer stocks.", two: "Food Corporation of India is constitutionally established under Article 280.", correct: 0, why: "Only statement 1 is correct. FCI is a statutory corporation created under the Food Corporations Act, 1964; Article 280 concerns the Finance Commission." },
];

const MAY: PairSeed[] = [
  { topic: "Sikkim's fully literate status", category: "polity", one: "Literacy rate is distinct from school enrolment and learning outcomes.", two: "Adult-literacy campaigns can complement formal schooling by addressing people who missed school-age education.", correct: 2, why: "Both are correct. Literacy recognition is valuable, but education quality, functional literacy and lifelong learning remain separate policy challenges." },
  { topic: "WMO's global-temperature outlook", category: "env", one: "The World Meteorological Organization is a specialised agency of the United Nations.", two: "A multi-year climate outlook predicts the exact weather on each day of the forecast period.", correct: 0, why: "Only statement 1 is correct. Climate outlooks describe probabilities and averages, not exact daily weather years in advance." },
  { topic: "trauma care as a fundamental-right issue", category: "polity", one: "Article 21 has been interpreted to include timely emergency medical care.", two: "A hospital may lawfully refuse every accident victim until police formalities are completed.", correct: 0, why: "Only statement 1 is correct. Life-saving treatment cannot be subordinated to procedural delay." },
  { topic: "the upgraded PM-WANI framework", category: "st", one: "PM-WANI seeks to expand public Wi-Fi through interoperable public data offices.", two: "A public data office is required to obtain a telecom-service-provider licence identical to a mobile operator's licence.", correct: 0, why: "Only statement 1 is correct. The architecture lowers entry barriers for distributed Wi-Fi access while relying on authorised network and registry entities." },
  { topic: "SARTHAK-PDS", category: "polity", one: "Digitising the public distribution system can improve portability, stock visibility and beneficiary authentication.", two: "Technology alone eliminates exclusion errors, connectivity failures and grievance-redress needs.", correct: 0, why: "Only statement 1 is correct. Digital PDS systems need offline safeguards, data correction and accessible grievance mechanisms." },
  { topic: "special intensive revision of electoral rolls", category: "polity", one: "Article 326 connects adult suffrage with elections to the Lok Sabha and State Assemblies.", two: "Electoral-roll revision must balance roll purity with safeguards against arbitrary disenfranchisement.", correct: 2, why: "Both are correct. Accurate rolls and inclusive, procedurally fair voter registration are both constitutional-democratic requirements." },
  { topic: "the Quad's Indo-Pacific initiatives", category: "world", one: "The Quad comprises India, Australia, Japan and the United States.", two: "Its cooperation extends beyond defence to areas such as health, infrastructure, technology and maritime awareness.", correct: 2, why: "Both are correct. The Quad is a flexible strategic grouping with a broad public-goods agenda." },
  { topic: "India-US critical-minerals cooperation", category: "economy", one: "Criticality depends on economic importance and supply-chain vulnerability, not geological scarcity alone.", two: "Processing and refining capacity can be as strategically important as access to ore deposits.", correct: 2, why: "Both are correct. Concentrated processing chains can create dependencies even where mineral resources exist in several countries." },
  { topic: "a State Uniform Civil Code bill", category: "polity", one: "Article 44 places a Uniform Civil Code among the Directive Principles of State Policy.", two: "Directive Principles are directly enforceable by courts in the same manner as Fundamental Rights.", correct: 0, why: "Only statement 1 is correct. Directive Principles guide governance but are not directly enforceable under Article 37." },
  { topic: "the NPT Review Conference", category: "world", one: "The Nuclear Non-Proliferation Treaty rests on non-proliferation, peaceful use and disarmament pillars.", two: "India is a party to the NPT as a recognised nuclear-weapon State.", correct: 0, why: "Only statement 1 is correct. India is not a party to the NPT, which recognises only states that tested before the treaty's cutoff." },
  { topic: "BHAVYA scheme guidelines", category: "economy", one: "Industrial cluster development can create shared infrastructure and agglomeration benefits.", two: "Cluster policy is irrelevant to small and medium enterprises because only large firms use common facilities.", correct: 0, why: "Only statement 1 is correct. Shared testing, logistics, training and utility infrastructure can be especially valuable to MSMEs." },
  { topic: "the World Health Assembly", category: "world", one: "It is the decision-making body of the World Health Organization.", two: "Each WHO member state is represented in the Assembly.", correct: 2, why: "Both are correct. The WHA sets policy, approves budgets and considers major global-health agreements and programmes." },
  { topic: "the International Big Cat Alliance", category: "env", one: "It promotes cooperation for conservation of seven major big-cat species.", two: "Its scope is limited to tiger-range countries and excludes lions, leopards and cheetahs.", correct: 0, why: "Only statement 1 is correct. The alliance covers tiger, lion, leopard, snow leopard, cheetah, jaguar and puma." },
  { topic: "China's Shenzhou programme", category: "st", one: "Shenzhou missions support crewed operations associated with China's space station.", two: "A crewed spacecraft must manage launch, orbital life support, rendezvous and atmospheric re-entry risks.", correct: 2, why: "Both are correct. Shenzhou is the human-spaceflight vehicle for China's Tiangong-era operations." },
  { topic: "RBI's surplus transfer to the Union government", category: "economy", one: "The transfer is governed by the Reserve Bank's economic-capital framework and balance-sheet position.", two: "A central-bank surplus transfer is the same as the government imposing a tax on private bank deposits.", correct: 0, why: "Only statement 1 is correct. It is a distribution from RBI's own income and provisions, not a tax on depositors." },
  { topic: "the Agni-1 missile", category: "st", one: "Agni-1 is a road-mobile, surface-to-surface ballistic missile.", two: "Ballistic missiles spend most of their flight under continuous aerodynamic lift like cruise missiles.", correct: 0, why: "Only statement 1 is correct. Ballistic missiles follow a ballistic trajectory after powered flight, unlike air-breathing cruise missiles." },
  { topic: "employment in the unincorporated sector", category: "economy", one: "Unincorporated enterprises include many household and small non-corporate establishments.", two: "Employment growth alone proves that all jobs in the sector are formal, productive and covered by social security.", correct: 0, why: "Only statement 1 is correct. Job quantity must be analysed alongside earnings, productivity, registration and protection." },
  { topic: "UPI's share in digital payments", category: "economy", one: "UPI is operated by the National Payments Corporation of India.", two: "A high share by transaction volume necessarily means an equally high share by transaction value.", correct: 0, why: "Only statement 1 is correct. Volume and value shares differ because payment systems serve different average ticket sizes." },
  { topic: "E30 petrol standards", category: "env", one: "E30 denotes a petrol blend containing up to 30 percent ethanol by volume.", two: "Higher ethanol blends can require attention to vehicle-material compatibility, calibration and fuel efficiency.", correct: 2, why: "Both are correct. Blend expansion must be matched by technical standards and compatible vehicle fleets." },
  { topic: "the SMILE space mission", category: "st", one: "It is a joint mission involving the Chinese Academy of Sciences and the European Space Agency.", two: "Its observations are intended to improve understanding of solar-wind interaction with Earth's magnetosphere.", correct: 2, why: "Both are correct. SMILE uses coordinated imaging to study large-scale magnetospheric dynamics." },
  { topic: "a hydrogen-powered train", category: "env", one: "A fuel-cell train converts hydrogen's chemical energy into electricity, with water as the point-of-use product.", two: "Its overall climate footprint is independent of how the hydrogen is produced.", correct: 0, why: "Only statement 1 is correct. Lifecycle emissions differ sharply between fossil-based and renewable hydrogen." },
  { topic: "India's semiconductor roadmap", category: "st", one: "Semiconductor resilience includes design, fabrication, packaging, materials, equipment and skilled workers.", two: "Domestic value addition can rise only if every input is produced within one factory.", correct: 0, why: "Only statement 1 is correct. Semiconductor ecosystems are networked, and value addition can deepen across many specialised firms." },
  { topic: "India-South Korea CEPA negotiations", category: "economy", one: "CEPA can cover goods, services, investment and economic cooperation.", two: "Rules of origin help prevent goods from obtaining preferences through minimal trans-shipment.", correct: 2, why: "Both are correct. Preferential trade agreements rely on origin rules to identify genuinely eligible products." },
  { topic: "evidence of ancient Gondwana wildfires", category: "geo", one: "Charcoal and altered plant material in geological strata can indicate palaeowildfires.", two: "Gondwana once included India together with landmasses such as Africa, Antarctica, Australia and South America.", correct: 2, why: "Both are correct. Geological proxies preserve fire history, while Gondwana's breakup shaped India's long tectonic journey." },
  { topic: "the Kali night frog", category: "env", one: "The Western Ghats are a global biodiversity hotspot with high amphibian endemism.", two: "Amphibians can act as sensitive indicators because they depend on both aquatic and terrestrial environments.", correct: 2, why: "Both are correct. Restricted ranges and permeable skin make many amphibians especially vulnerable to environmental change." },
];

const JUNE: PairSeed[] = [
  { topic: "the Unified Health Interface", category: "st", one: "UHI is an interoperability layer associated with the Ayushman Bharat Digital Mission.", two: "It is intended to enable open discovery and exchange of digital health services across participating applications.", correct: 2, why: "Both are correct. UHI applies open-network principles to digital health-service discovery and transactions." },
  { topic: "SUMAN Roadmap 2030", category: "polity", one: "SUMAN focuses on respectful, assured and zero-cost maternal and newborn healthcare in public facilities.", two: "Maternal health outcomes depend only on institutional delivery and not on antenatal, referral or postnatal care.", correct: 0, why: "Only statement 1 is correct. A continuum of care—from pregnancy through emergency referral and the postnatal period—is essential." },
  { topic: "Bharat Taxi", category: "economy", one: "A cooperative mobility platform can give drivers a collective ownership and governance role.", two: "Every cooperative must distribute voting power strictly in proportion to outside investor capital.", correct: 0, why: "Only statement 1 is correct. Cooperative models typically privilege member control rather than investor-weighted corporate voting." },
  { topic: "the Green Urea Roadmap", category: "env", one: "Conventional urea production relies heavily on ammonia derived from hydrogen and nitrogen.", two: "Using renewable hydrogen for ammonia can reduce emissions if the electricity and supply chain are genuinely low-carbon.", correct: 2, why: "Both are correct. Green urea depends on decarbonising the hydrogen-ammonia stage and assessing the full lifecycle." },
  { topic: "Netra AEW&C", category: "st", one: "An airborne early-warning and control system extends radar surveillance and battle-management coverage from the air.", two: "Such a system is useful only for weather observation and cannot support air-defence coordination.", correct: 0, why: "Only statement 1 is correct. AEW&C aircraft detect tracks, share situational awareness and support command and control." },
  { topic: "the BRICS Energy Ministers' Meeting", category: "world", one: "BRICS energy cooperation can include energy security, transition finance, technology and critical minerals.", two: "All BRICS members have identical energy mixes and therefore face no coordination trade-offs.", correct: 0, why: "Only statement 1 is correct. Members differ widely in resources, demand, development level and transition pathways." },
  { topic: "Air Suvidha 2.0", category: "polity", one: "Digital passenger-health systems can support risk-based public-health screening at ports of entry.", two: "Collection of traveller health data removes the need for purpose limitation, retention limits or security safeguards.", correct: 0, why: "Only statement 1 is correct. Public-health utility must be balanced with data protection and proportionality." },
  { topic: "Haldia as an immigration post", category: "geo", one: "Haldia is a riverine port complex in West Bengal connected to the Hooghly estuary.", two: "Designation as an immigration post can facilitate authorised international movement of crew or passengers.", correct: 2, why: "Both are correct. Immigration-post status supports lawful cross-border movement at a designated port." },
  { topic: "amended FCRA rules", category: "polity", one: "The Foreign Contribution (Regulation) Act regulates receipt and use of foreign contribution by specified persons and organisations.", two: "FCRA registration creates an unrestricted constitutional right to receive foreign funds for any purpose.", correct: 0, why: "Only statement 1 is correct. Receipt remains subject to statutory eligibility, permitted purpose, reporting and government oversight." },
  { topic: "ship recycling", category: "env", one: "Ship recycling can recover steel and equipment but may expose workers and coasts to hazardous materials.", two: "The Hong Kong Convention addresses safe and environmentally sound recycling of ships.", correct: 2, why: "Both are correct. Recycling's circular-economy benefits depend on inventory, worker-safety and pollution controls." },
  { topic: "International Day of Yoga", category: "history", one: "It is observed on 21 June following a United Nations General Assembly resolution.", two: "Yoga traditions are confined to physical postures and exclude ethical, meditative or breathing practices.", correct: 0, why: "Only statement 1 is correct. Yoga encompasses diverse physical, ethical, contemplative and respiratory traditions." },
  { topic: "Exercise Khaan Quest", category: "world", one: "It is a multinational peacekeeping exercise hosted by Mongolia.", two: "Peacekeeping training can include civil-military coordination, protection of civilians and field procedures.", correct: 2, why: "Both are correct. Khaan Quest builds interoperability for UN-style peace-support operations." },
  { topic: "Uzbekistan joining the New Development Bank", category: "world", one: "The NDB was established by the BRICS countries.", two: "Its membership is legally restricted forever to the five original BRICS members.", correct: 0, why: "Only statement 1 is correct. NDB membership has expanded beyond its founding shareholders." },
  { topic: "QS World University Rankings", category: "polity", one: "Rankings combine indicators and weights that can change institutional positions even without a sudden change in teaching quality.", two: "A university's rank is a direct constitutional measure of its legal autonomy.", correct: 0, why: "Only statement 1 is correct. Rankings are methodological comparisons, not legal or constitutional classifications." },
  { topic: "the economic value of homemakers' work", category: "economy", one: "Unpaid household and care work is generally outside conventional GDP when no market transaction is recorded.", two: "Time-use surveys can help estimate the scale and distribution of unpaid work.", correct: 2, why: "Both are correct. National accounts and welfare analysis treat unpaid care differently, making time-use evidence important." },
  { topic: "the India-UK CETA", category: "economy", one: "A trade agreement can phase tariff reductions over different schedules for different products.", two: "An agreement's entry into force may occur after signature once domestic legal procedures are completed.", correct: 2, why: "Both are correct. Negotiation conclusion, signature, ratification and implementation are distinct stages." },
  { topic: "the Indian Ocean Rim Association", category: "world", one: "IORA is an intergovernmental organisation centred on Indian Ocean regional cooperation.", two: "Its agenda can include maritime safety, trade facilitation, disaster risk and the blue economy.", correct: 2, why: "Both are correct. IORA's broad cooperative agenda reflects the interconnected economic and security interests of the ocean rim." },
  { topic: "Tripura's Sarinda GI tag", category: "history", one: "A geographical indication identifies goods whose quality, reputation or characteristic is linked to geographical origin.", two: "A GI is identical to a patent granted to the first individual inventor for twenty years.", correct: 0, why: "Only statement 1 is correct. GI rights are collective origin-linked identifiers, whereas patents protect qualifying inventions." },
  { topic: "the India-Japan Joint Crediting Mechanism", category: "env", one: "Article 6 of the Paris Agreement provides pathways for voluntary international cooperation on mitigation outcomes.", two: "Crediting mechanisms require robust accounting to reduce the risk of double counting.", correct: 2, why: "Both are correct. Environmental integrity depends on authorisation, corresponding adjustments and transparent measurement." },
  { topic: "the Long Range Land Attack Cruise Missile", category: "st", one: "A cruise missile sustains powered flight within the atmosphere and can follow a relatively low-altitude path.", two: "It follows an unpowered exo-atmospheric ballistic arc for most of its journey.", correct: 0, why: "Only statement 1 is correct. Statement 2 describes a typical ballistic-missile flight profile rather than a cruise missile." },
  { topic: "India's first Easy Connect flight", category: "geo", one: "A simplified transfer product can reduce repeated passenger processing at connecting airports.", two: "International air connectivity still requires compliance with immigration, customs and security rules where applicable.", correct: 2, why: "Both are correct. Facilitation can streamline procedures but cannot erase sovereign border and aviation-security requirements." },
  { topic: "the Future Skills Index", category: "economy", one: "A future-skills assessment may examine digital, analytical, green and human capabilities relevant to changing labour markets.", two: "A country's rank alone reveals the distribution of skills across gender, region and income groups.", correct: 0, why: "Only statement 1 is correct. Aggregate ranks can conceal internal access and outcome inequalities." },
  { topic: "smart seed-coating technology", category: "st", one: "Seed coatings can deliver micronutrients, protectants or beneficial microbes close to the germinating seed.", two: "Any coating is environmentally safe regardless of chemical composition, dose or persistence.", correct: 0, why: "Only statement 1 is correct. Benefits and risks depend on formulation, exposure and ecological effects." },
  { topic: "zinc-ion batteries", category: "st", one: "Zinc-ion systems can use aqueous electrolytes and potentially offer safety and material-abundance advantages.", two: "Rechargeable zinc systems face no dendrite, cathode-stability or cycle-life challenges.", correct: 0, why: "Only statement 1 is correct. Research continues precisely because several electrochemical and durability problems remain." },
  { topic: "the maternal and newborn health continuum", category: "polity", one: "Preventing maternal deaths requires functioning referral transport and emergency obstetric care in addition to routine check-ups.", two: "Neonatal outcomes are unrelated to maternal nutrition, birth care or early breastfeeding.", correct: 0, why: "Only statement 1 is correct. Maternal and newborn outcomes are biologically and programmatically linked across the continuum of care." },
];

export const CURRENT_AFFAIRS_2026: Record<string, QuizSet[]> = {
  "2026-01": makeSets("January", JANUARY),
  "2026-02": makeSets("February", FEBRUARY),
  "2026-03": makeSets("March", MARCH),
  "2026-04": makeSets("April", APRIL),
  "2026-05": makeSets("May", MAY),
  "2026-06": makeSets("June", JUNE),
};

export function getCurrentAffairsQuiz(month: string, slug: string) {
  return CURRENT_AFFAIRS_2026[month]?.find((set) => set.slug === slug)?.quiz ?? null;
}

const STATIC_SEEDS: Record<string, { label: string; description: string; category: string; seeds: PairSeed[] }> = {
  polity: {
    label: "Polity & Constitution",
    description: "Institutions, rights, federalism and constitutional procedure.",
    category: "polity",
    seeds: [
      { topic: "a Money Bill", category: "polity", one: "The Speaker's certification is required for a bill to be treated as a Money Bill.", two: "Rajya Sabha may recommend amendments but cannot reject or amend a Money Bill on its own authority.", correct: 2, why: "Both are correct under Articles 109 and 110. Rajya Sabha has a recommendatory role and a fourteen-day window." },
      { topic: "ordinance-making power", category: "polity", one: "The President may promulgate an ordinance when both Houses of Parliament are in session.", two: "An ordinance has the same force as an Act but is subject to parliamentary approval and judicial review.", correct: 1, why: "Only statement 2 is correct. The President's ordinance power is available when both Houses are not simultaneously in session." },
      { topic: "the anti-defection law", category: "polity", one: "It is contained in the Tenth Schedule.", two: "A merger exception requires at least two-thirds of the members of the legislature party.", correct: 2, why: "Both are correct. The law addresses defection while recognising a two-thirds merger exception." },
      { topic: "the Comptroller and Auditor General", category: "polity", one: "The CAG audits expenditure from the Consolidated Fund of India and of the States.", two: "The CAG is removable in the same manner and on the same grounds as a Supreme Court judge.", correct: 2, why: "Both are correct. These safeguards support institutional independence in public audit." },
      { topic: "Fundamental Rights during an Emergency", category: "polity", one: "Articles 20 and 21 cannot be suspended through an order under Article 359.", two: "Article 19 is automatically suspended during every kind of national emergency, including one declared solely on armed rebellion.", correct: 0, why: "Only statement 1 is correct. Article 19's automatic suspension under Article 358 is limited to emergency on war or external aggression." },
      { topic: "inter-State water disputes", category: "polity", one: "Article 262 permits Parliament to provide for adjudication of inter-State river-water disputes.", two: "Parliament may exclude the jurisdiction of the Supreme Court and other courts over such disputes by law.", correct: 2, why: "Both are correct. Article 262 supports specialised statutory adjudication and jurisdictional exclusion." },
    ],
  },
  economy: {
    label: "Indian Economy",
    description: "Money, banking, public finance, growth and external sector.",
    category: "economy",
    seeds: [
      { topic: "core inflation", category: "economy", one: "It commonly excludes food and fuel because their prices are often volatile.", two: "It is the inflation measure formally targeted by India's Monetary Policy Committee.", correct: 0, why: "Only statement 1 is correct. India's flexible inflation target is specified in terms of headline CPI inflation." },
      { topic: "the current account", category: "economy", one: "It records trade in goods and services, primary income and transfers.", two: "Foreign direct investment inflows are recorded in the current account.", correct: 0, why: "Only statement 1 is correct. FDI belongs to the financial account of the balance of payments." },
      { topic: "open market operations", category: "economy", one: "RBI purchases of government securities can inject durable liquidity.", two: "OMO transactions are identical to changes in the statutory liquidity ratio.", correct: 0, why: "Only statement 1 is correct. OMOs are market transactions, whereas SLR is a regulatory reserve requirement." },
      { topic: "fiscal deficit", category: "economy", one: "It broadly measures total expenditure minus non-debt receipts.", two: "A fiscal deficit of zero necessarily means the government has no outstanding public debt.", correct: 0, why: "Only statement 1 is correct. Deficit is a flow for a period, whereas debt is an accumulated stock." },
      { topic: "real and nominal GDP", category: "economy", one: "Nominal GDP values output at current prices.", two: "Real GDP removes the effect of price changes using constant-price valuation.", correct: 2, why: "Both are correct. The distinction separates changes in quantities from changes in the general price level." },
      { topic: "minimum reserve requirements", category: "economy", one: "CRR is maintained by banks as cash balances with RBI.", two: "SLR can include specified liquid assets held by banks themselves.", correct: 2, why: "Both are correct. CRR and SLR differ in the form and custody of required reserves." },
    ],
  },
  history: {
    label: "History & Culture",
    description: "Ancient, medieval, modern India and art and culture.",
    category: "history",
    seeds: [
      { topic: "Ashokan inscriptions", category: "history", one: "Most major rock edicts were composed in Prakrit and written in Brahmi script.", two: "North-western inscriptions also used Kharosthi, Greek or Aramaic in some locations.", correct: 2, why: "Both are correct. Ashoka communicated in regionally appropriate languages and scripts across the empire." },
      { topic: "the Permanent Settlement", category: "history", one: "It was introduced in Bengal under Lord Cornwallis.", two: "It fixed land revenue demand permanently with zamindars recognised as proprietors.", correct: 2, why: "Both are correct. The 1793 settlement reshaped agrarian relations and colonial revenue collection." },
      { topic: "the Ilbert Bill controversy", category: "history", one: "It concerned the authority of Indian judges over European British subjects.", two: "The controversy exposed racial privilege in the colonial legal system.", correct: 2, why: "Both are correct. European opposition forced a compromise and became a political lesson for early nationalists." },
      { topic: "Sangam literature", category: "history", one: "It is an important source for early historic Tamil society.", two: "The landscapes called tinai linked ecology with occupations, emotions and social life.", correct: 2, why: "Both are correct. Sangam texts organise human experience through distinct ecological-cultural zones." },
      { topic: "the Government of India Act, 1935", category: "history", one: "It introduced provincial autonomy.", two: "Its proposed all-India federation came fully into operation before Independence.", correct: 0, why: "Only statement 1 is correct. The federation never became operational, though provincial autonomy was implemented." },
      { topic: "the Cabinet Mission Plan", category: "history", one: "It proposed a Union handling defence, foreign affairs and communications.", two: "It rejected an immediate sovereign Pakistan while proposing provincial groupings.", correct: 2, why: "Both are correct. The plan sought a loose Indian Union as an alternative to partition." },
    ],
  },
  geography: {
    label: "Geography",
    description: "Physical processes, Indian geography and mapping logic.",
    category: "geo",
    seeds: [
      { topic: "western disturbances", category: "geo", one: "They originate as extra-tropical systems in the Mediterranean-West Asian region.", two: "They are important for winter precipitation over north-western India and Himalayan snowfall.", correct: 2, why: "Both are correct. Their eastward movement influences rabi crops, cold waves and mountain snow." },
      { topic: "ocean upwelling", category: "geo", one: "It brings colder, nutrient-rich subsurface water toward the surface.", two: "Major upwelling zones are often associated with productive fisheries.", correct: 2, why: "Both are correct. Nutrient delivery supports phytoplankton and higher marine productivity." },
      { topic: "temperature inversion", category: "geo", one: "It occurs when temperature increases with height in a layer of the atmosphere.", two: "It can trap pollutants near the surface under stable conditions.", correct: 2, why: "Both are correct. Inversions suppress vertical mixing and worsen low-level pollution episodes." },
      { topic: "the Coriolis force", category: "geo", one: "Its deflection is to the right in the Northern Hemisphere and to the left in the Southern Hemisphere.", two: "It is zero at the equator.", correct: 2, why: "Both are correct. Coriolis strength varies with latitude and vanishes at zero latitude." },
      { topic: "black soils", category: "geo", one: "They are strongly associated with the Deccan Trap basalt region.", two: "Their high clay content produces shrink-swell behaviour and deep cracks in dry periods.", correct: 2, why: "Both are correct. These vertisols retain moisture but present distinctive drainage and tillage challenges." },
      { topic: "river capture", category: "geo", one: "It occurs when one drainage system diverts the headwaters of another.", two: "It can result from differential erosion and headward extension of a stream.", correct: 2, why: "Both are correct. River piracy reorganises drainage networks through geomorphic competition." },
    ],
  },
  environment: {
    label: "Environment & Ecology",
    description: "Ecology, conservation, pollution and climate governance.",
    category: "env",
    seeds: [
      { topic: "ecological succession", category: "env", one: "Primary succession begins where a developed soil is absent.", two: "Secondary succession can proceed after disturbance where soil or propagules remain.", correct: 2, why: "Both are correct. Initial conditions strongly influence the pace and pathway of community change." },
      { topic: "biomagnification", category: "env", one: "It is the increase in concentration of certain persistent contaminants at higher trophic levels.", two: "It is identical to the increase of total biomass from predators to producers.", correct: 0, why: "Only statement 1 is correct. Biomagnification concerns contaminant concentration, not ecosystem biomass pyramids." },
      { topic: "Ramsar sites", category: "env", one: "A site may remain under national sovereignty after Ramsar designation.", two: "The Montreux Record identifies Ramsar sites where ecological character has changed or may change adversely.", correct: 2, why: "Both are correct. Ramsar is a conservation commitment, and the Montreux Record highlights sites needing priority attention." },
      { topic: "carbon markets", category: "env", one: "A cap-and-trade system fixes an emissions cap and allows trading of allowances.", two: "A carbon tax directly fixes the quantity of emissions and lets the market determine the tax rate.", correct: 0, why: "Only statement 1 is correct. A carbon tax fixes the price while emissions quantity responds." },
      { topic: "environmental DNA", category: "env", one: "eDNA can be collected from water, soil or air without capturing the target organism.", two: "Detection of DNA always proves the organism is alive and breeding at the sampled location.", correct: 0, why: "Only statement 1 is correct. DNA can persist or move, so ecological interpretation requires careful sampling and validation." },
      { topic: "coral bleaching", category: "env", one: "Heat stress can cause corals to expel symbiotic algae.", two: "A bleached coral is necessarily dead at the moment bleaching becomes visible.", correct: 0, why: "Only statement 1 is correct. Bleached corals are stressed and may recover if conditions improve, though prolonged stress can kill them." },
    ],
  },
  st: {
    label: "Science & Technology",
    description: "Space, biotechnology, computing and emerging technologies.",
    category: "st",
    seeds: [
      { topic: "CRISPR-Cas systems", category: "st", one: "Guide RNA can direct a Cas enzyme to a complementary nucleic-acid sequence.", two: "Genome editing raises off-target, delivery and heritable-change concerns.", correct: 2, why: "Both are correct. CRISPR is precise but not risk-free, especially in therapeutic and germline contexts." },
      { topic: "quantum entanglement", category: "st", one: "Entangled particles can exhibit correlations not explained by classical local hidden-variable theories.", two: "Entanglement permits controllable faster-than-light communication.", correct: 0, why: "Only statement 1 is correct. Quantum correlations do not enable superluminal signalling." },
      { topic: "geostationary satellites", category: "st", one: "They orbit over the equator with a period equal to Earth's rotation.", two: "A single geostationary satellite can provide direct coverage of the geographic poles.", correct: 0, why: "Only statement 1 is correct. Low elevation angles make polar coverage poor or impossible from geostationary orbit." },
      { topic: "mRNA vaccines", category: "st", one: "They deliver genetic instructions that cells use temporarily to produce an antigen.", two: "The vaccine mRNA must enter the cell nucleus and integrate into chromosomal DNA to work.", correct: 0, why: "Only statement 1 is correct. mRNA functions in the cytoplasm and is degraded without genomic integration." },
      { topic: "large language models", category: "st", one: "They learn statistical patterns from large corpora and generate outputs token by token.", two: "Fluent output guarantees factual accuracy and absence of bias.", correct: 0, why: "Only statement 1 is correct. LLMs can hallucinate, inherit biases and require evaluation and grounding." },
      { topic: "green hydrogen", category: "st", one: "It is commonly produced by electrolysis powered by renewable electricity.", two: "Its climate performance can be affected by electrolyser efficiency, electricity source and water management.", correct: 2, why: "Both are correct. The label alone is insufficient without credible lifecycle accounting." },
    ],
  },
  bihar: {
    label: "Bihar Special",
    description: "History, geography, economy and institutions of Bihar.",
    category: "bihar",
    seeds: [
      { topic: "the Kosi river", category: "bihar", one: "It carries heavy sediment from the young Himalayas and has shifted channels across its megafan.", two: "It is a right-bank tributary of the Ganga.", correct: 0, why: "Only statement 1 is correct. The Kosi joins the Ganga from the north and is therefore a left-bank tributary." },
      { topic: "Nalanda Mahavihara", category: "bihar", one: "It flourished under Gupta and later Pala patronage.", two: "Xuanzang studied at Nalanda and recorded aspects of its intellectual life.", correct: 2, why: "Both are correct. Nalanda became an international centre of Buddhist and multidisciplinary learning." },
      { topic: "Champaran Satyagraha", category: "bihar", one: "It was associated with the grievances of indigo cultivators under the tinkathia system.", two: "It marked Gandhi's first major satyagraha in India.", correct: 2, why: "Both are correct. The 1917 movement linked peasant inquiry, mobilisation and non-violent pressure." },
      { topic: "Bihar's legislative structure", category: "bihar", one: "Bihar has a bicameral State legislature.", two: "The Legislative Council is a permanent House with one-third of its members retiring every two years.", correct: 2, why: "Both are correct. Bihar is among the States with both an Assembly and a Legislative Council." },
      { topic: "the Barabar caves", category: "bihar", one: "They contain some of India's earliest surviving rock-cut architecture.", two: "Several caves were dedicated to the Ajivikas during the Mauryan period.", correct: 2, why: "Both are correct. Their polished interiors and Ashokan-era inscriptions are important features." },
      { topic: "Bihar's agricultural markets", category: "bihar", one: "Bihar repealed its APMC Act in 2006.", two: "Repeal automatically ensured universal competitive markets, storage and price discovery for all farmers.", correct: 0, why: "Only statement 1 is correct. Removing regulation does not by itself create infrastructure, buyers, information or bargaining power." },
    ],
  },
  world: {
    label: "International Relations",
    description: "Institutions, groupings, diplomacy and global governance.",
    category: "world",
    seeds: [
      { topic: "the UN Security Council", category: "world", one: "It has five permanent members with veto power.", two: "Procedural decisions require concurring votes of all permanent members.", correct: 0, why: "Only statement 1 is correct. The veto applies to substantive decisions, not procedural matters." },
      { topic: "the International Court of Justice", category: "world", one: "It settles legal disputes between States that consent to its jurisdiction.", two: "It prosecutes individuals for genocide and crimes against humanity.", correct: 0, why: "Only statement 1 is correct. Individual criminal responsibility is handled by criminal tribunals such as the ICC, not the ICJ." },
      { topic: "the IMF's Special Drawing Rights", category: "world", one: "SDRs are international reserve assets based on a basket of major currencies.", two: "They are a currency used by the public to purchase goods in ordinary domestic markets.", correct: 0, why: "Only statement 1 is correct. SDRs are accounting reserve assets held and exchanged by official participants." },
      { topic: "ASEAN", category: "world", one: "The ASEAN Secretariat is located in Jakarta.", two: "Consensus and non-interference have been important features of the ASEAN way.", correct: 2, why: "Both are correct. ASEAN combines institutional cooperation with a distinctive consensus-oriented diplomatic culture." },
      { topic: "the World Trade Organization", category: "world", one: "Its dispute-settlement system deals with obligations under covered trade agreements.", two: "The WTO directly sets every member's domestic corporate-tax rate.", correct: 0, why: "Only statement 1 is correct. WTO rules shape trade policy but do not centrally determine domestic corporate taxes." },
      { topic: "the African Union", category: "world", one: "Its headquarters is in Addis Ababa.", two: "Agenda 2063 is the continent's long-term development and integration framework.", correct: 2, why: "Both are correct. The AU combines political cooperation with continental transformation goals." },
    ],
  },
};

export const STATIC_QUIZZES: QuizSet[] = Object.entries(STATIC_SEEDS).map(([slug, subject]) => ({
  slug,
  title: subject.label,
  description: subject.description,
  categories: [subject.category],
  quiz: buildQuiz(`${subject.label} - UPSC Foundation Test`, subject.seeds, 720),
}));

export function getStaticQuiz(slug: string) {
  return STATIC_QUIZZES.find((set) => set.slug === slug)?.quiz ?? null;
}

const PYQ_SEEDS: Record<string, { title: string; description: string; seeds: PairSeed[] }> = {
  "upsc-polity": {
    title: "UPSC PYQ Patterns - Polity",
    description: "Paraphrased constitutional patterns repeatedly tested in Prelims.",
    seeds: STATIC_SEEDS.polity.seeds,
  },
  "upsc-economy": {
    title: "UPSC PYQ Patterns - Economy",
    description: "Conceptual elimination across money, banking and public finance.",
    seeds: STATIC_SEEDS.economy.seeds,
  },
  "upsc-environment": {
    title: "UPSC PYQ Patterns - Environment",
    description: "Ecology and convention logic modelled on recurring UPSC themes.",
    seeds: STATIC_SEEDS.environment.seeds,
  },
  "bpsc-bihar": {
    title: "BPSC PYQ Patterns - Bihar Special",
    description: "Bihar-linked factual and conceptual traps for BPSC Prelims.",
    seeds: STATIC_SEEDS.bihar.seeds,
  },
};

export const PYQ_QUIZZES: QuizSet[] = Object.entries(PYQ_SEEDS).map(([slug, set]) => ({
  slug,
  title: set.title,
  description: set.description,
  categories: [...new Set(set.seeds.map((question) => question.category))],
  quiz: buildQuiz(set.title, set.seeds, 720),
}));

export function getPyqQuiz(slug: string) {
  return PYQ_QUIZZES.find((set) => set.slug === slug)?.quiz ?? null;
}
