create table if not exists public.helpdesk_events (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null,
  role text not null check (role in ('user', 'assistant')),
  message text not null,
  intent text not null default 'general',
  profile jsonb not null default '{}'::jsonb,
  lead_ready boolean not null default false,
  needs_human boolean not null default false,
  page_path text,
  created_at timestamptz not null default now()
);

create index if not exists helpdesk_events_conversation_created_idx
  on public.helpdesk_events (conversation_id, created_at);

alter table public.helpdesk_events enable row level security;

grant insert on table public.helpdesk_events to anon, authenticated;
grant usage, select on sequence public.helpdesk_events_id_seq to anon, authenticated;

revoke select, update, delete on table public.helpdesk_events from anon, authenticated;

drop policy if exists "allow helpdesk event inserts" on public.helpdesk_events;
create policy "allow helpdesk event inserts"
  on public.helpdesk_events
  for insert
  to anon, authenticated
  with check (true);

-- Public clients may append events only. They cannot read, edit or delete helpdesk data.
-- Read conversations from trusted server/admin tooling instead.
